version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
  test_and_coverage:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: pip install coveralls --user
      - run: coverage run -m pytest
      - run: coverage report
      - run: coverage html
      - run: coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_and_coverage:
          requires:
            - build