version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
  test_and_coverage:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: pip install pytest coveralls --user
      - run: $HOME/.local/bin/coverage run -m pytest --junitxml=test-reports/junit.xml
      - run: $HOME/.local/bin/coverage report
      - run: $HOME/.local/bin/coverage html
      - run: $HOME/.local/bin/coveralls

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_and_coverage:
          requires:
            - build