version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
  test_and_coverage:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: pip install pytest --user
      - run: pytest

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_and_coverage:
          requires:
            - build